REM INSERTING into FM_CALENDARS_HOLIDAYS
SET DEFINE OFF;
Insert into FM_CALENDARS_HOLIDAYS (NAME,VERSION_NUMBER,CREATED,CREATED_BY,LAST_UPDATED,LAST_UPDATED_BY,LONG_NAME,ISO_CODE) values ('AHM',64,to_date('09-02-22','DD-MM-RR'),'System',to_date('09-02-22','DD-MM-RR'),'System','AHM','AHM');
